function hp_sub = drawpanel(handle,initData,initEncoder,stepperHandle)
%
% Function: 
%
veloLim = num2str(initData(1));
acceLim =  num2str(initData(2));
currLim =  num2str(initData(3));
serNum = num2str(initData(4));
step = num2str(initData(5));
position = num2str(initData(6),'%0.4f');
sliderPosition = round(initData(6)*1000);

hp_sub.h_active =   uicontrol('Parent',handle,...       % x axis active indicator
                            'Style','push',...
                            'unit','pixel',...
                            'Position',[10 50 20 20],...
                            'Enable','inactive');

hp_sub.h_veloLimTxt =   uicontrol('Parent',handle,...   % velocity Limit Label
                            'Style','text',...
                            'unit','pixel',...
                            'Position',[40 90 100 20],...
                            'HorizontalAlignment','right',...
                            'Backgroundcolor',get(handle,'Backgroundcolor'),...
                            'FontSize',12,...
                            'String','Velocity Limit:');
hp_sub.h_veloLimEdt =   uicontrol('Parent',handle,...   % velocity Limit edit
                            'Style','edit',...
                            'unit','pixel',...
                            'Position',[145 90 75 20],...
                            'FontSize',12,...
                            'String',veloLim);
                        
hintInfo = '<html>Regular value: ~70000 - 94.79 mm/min <br>value: 75 - 0.1 mm/min <br>value: 150 - 0.2 mm/min';
set(hp_sub.h_veloLimEdt, 'tooltip',hintInfo);

hp_sub.h_acceTxt =   uicontrol('Parent',handle,...   % Acceleration Label
                            'Style','text',...
                            'unit','pixel',...
                            'Position',[40 65 100 20],...
                            'HorizontalAlignment','right',...
                            'Backgroundcolor',get(handle,'Backgroundcolor'),...
                            'FontSize',12,...
                            'String','Acceleration:');
hp_sub.h_acceEdt =   uicontrol('Parent',handle,...   % Acceleration edit
                            'Style','edit',...
                            'unit','pixel',...
                            'Position',[145 65 75 20],...
                            'FontSize',12,...
                            'String',acceLim);
                        
hp_sub.h_currLimTxt =   uicontrol('Parent',handle,...    % Current Limit Label
                            'Style','text',...
                            'unit','pixel',...
                            'Position',[40 40 100 20],...
                            'HorizontalAlignment','right',...
                            'Backgroundcolor',get(handle,'Backgroundcolor'),...
                            'FontSize',12,...
                            'String','Current Limit:');
hp_sub.h_currLimEdt =   uicontrol('Parent',handle,...    % Current Limit edit
                            'Style','edit',...
                            'unit','pixel',...
                            'Position',[145 40 75 20],...
                            'FontSize',12,...
                            'String',currLim);

hp_sub.h_serNumTxt =   uicontrol('Parent',handle,...   % Serial number Label
                            'Style','text',...
                            'unit','pixel',...
                            'Position',[230 90 100 20],...
                            'HorizontalAlignment','right',...
                            'Backgroundcolor',get(handle,'Backgroundcolor'),...
                            'FontSize',12,...
                            'String','Serial Num:');
hp_sub.h_serNumEdt =   uicontrol('Parent',handle,...   % Serial number edit
                            'Style','edit',...
                            'unit','pixel',...
                            'Position',[335 90 75 20],...
                            'FontSize',12,...
                            'Enable','off',...
                            'String',serNum); 
                        
hp_sub.h_stepTxt =   uicontrol('Parent',handle,...   % Step Label
                            'Style','text',...
                            'unit','pixel',...
                            'Position',[230 65 100 20],...
                            'HorizontalAlignment','right',...
                            'Backgroundcolor',get(handle,'Backgroundcolor'),...
                            'FontSize',12,...
                            'String','Step:');
hp_sub.h_stepEdt =   uicontrol('Parent',handle,...   % Step edit
                            'Style','edit',...
                            'unit','pixel',...
                            'Position',[335 65 75 20],...
                            'FontSize',12,...
                            'String',step);  
                        
hp_sub.h_positionTxt =   uicontrol('Parent',handle,...   % Step Label
                            'Style','text',...
                            'unit','pixel',...
                            'Position',[230 40 100 20],...
                            'HorizontalAlignment','right',...
                            'Backgroundcolor',get(handle,'Backgroundcolor'),...
                            'FontSize',12,...
                            'String','Position:');
hp_sub.h_positionEdt =   uicontrol('Parent',handle,...   % Step edit
                            'Style','edit',...
                            'unit','pixel',...
                            'Position',[335 40 75 20],...
                            'FontSize',12,...
                            'String',position);
                        
sliderValMin = 0;
sliderValMax = 80000;                                             
hp_sub.h_slider =   uicontrol('Parent',handle,...    % Current Limit Label
                            'Style','slider',...
                            'Min',sliderValMin,'Max',sliderValMax,...
                            'SliderStep',[0.01 0.1],...
                            'Value',sliderPosition,...
                            'unit','pixel',...
                            'Interruptible','on',... 
                            'Position',[40 10 370 20]);   
% Add a listener for the value change of position
addlistener(hp_sub.h_positionEdt, 'String', 'PostSet', @positionValueChange);

    function positionValueChange(varargin)
        posValue = str2double(get(hp_sub.h_positionEdt,'string'));
        posValueS = round(posValue*1000);
        
        if posValueS > 80000
            set(hp_sub.h_slider,'value',80000);
            set(hp_sub.h_positionEdt,'String','80.0000');
            h_msg = msgbox('Please Input Value: 0 - 80!','Warning');
            WinOnTop( h_msg, true);
        elseif posValueS < 0
            set(hp_sub.h_slider,'value',0);
            set(hp_sub.h_positionEdt,'String','0.0000');
            h_msg = msgbox('Please Input Value: 0 - 80!','Warning');
            WinOnTop( h_msg, true);
        else
            if abs(get(hp_sub.h_slider,'value') - posValueS) > 1
                set(hp_sub.h_slider,'value',posValueS);
            end
            
        end
    end   
% Add a listener for the value change of velocity; acceleration; current
% limit
addlistener(hp_sub.h_veloLimEdt, 'String', 'PostSet', @upDateVeloLim);
addlistener(hp_sub.h_acceEdt,    'String', 'PostSet', @upDateAcceLim);
addlistener(hp_sub.h_currLimEdt, 'String', 'PostSet', @upDateCurrLim);


    
    
    function upDateVeloLim(varargin)
        veloLim_D = str2double(get(hp_sub.h_veloLimEdt, 'String'));
        calllib('phidget21', 'CPhidgetStepper_setVelocityLimit', stepperHandle, 0, veloLim_D);
    end

    function upDateAcceLim(varargin)
        acceLim_D = str2double(get(hp_sub.h_acceEdt, 'String'));
        calllib('phidget21', 'CPhidgetStepper_setAcceleration', stepperHandle, 0, acceLim_D);
    end

    function upDateCurrLim(varargin)
        currLim_D = str2double(get(hp_sub.h_currLimEdt, 'String'));
        calllib('phidget21', 'CPhidgetStepper_setCurrentLimit', stepperHandle, 0, currLim_D);
    end

encoderBtnColor = [0.94,0.94,0.94;0.14,0.64,0.14;];                                           
hp_sub.h_encoder =   uicontrol('Parent',handle,...   % Update
                            'Style','togglebutton',...
                            'unit','pixel',...
                            'Position',[420 60 65 40],...
                            'FontSize',10,...
                            'String','Encoder',...
                            'value',initEncoder,...
                            'BackgroundColor',encoderBtnColor(initEncoder+1,:));
                        
hp_sub.h_stop =   uicontrol('Parent',handle,...   % Set calibrate button
                            'Style','push',...
                            'unit','pixel',...
                            'Position',[420 16 65 40],...
                            'FontSize',10,...
                            'String','N/A');                 
                        
hp_sub.h_posMov =   uicontrol('Parent',handle,...   % Positive move
                            'Style','push',...
                            'unit','pixel',...
                            'Position',[490 60 65 40],...
                            'FontSize',11,...
                            'String','+');                         
hp_sub.h_negMov =   uicontrol('Parent',handle,...   % Negtive move
                            'Style','push',...
                            'unit','pixel',...
                            'Position',[490 16 65 40],...
                            'FontSize',11,...
                            'String','-');
end